### PR TITLE
Fix some text color in darkmode

### LINKED ISSUE #55: Some text are hard to seen or can't be seen in dark mode
I'm using version 1.0.0 right now. Here's what I found.

**In a group chat's people detail**
screen shot 2559-02-21 at 11 36 08 pm
**In a new messsage invitation**
screen shot 2559-02-21 at 11 44 41 pm

It's probably just a CSS issues. Can I give this a try? Is there anything I have to do to contribute to this project? (I'm quite new to OSS though)

### PR DESCRIPTION
**Pull request by lukyth**
I changed some CSS in order to fix #55 . Here's what it becomes.

**Before:**
screen shot 2559-02-21 at 11 36 08 pm
screen shot 2559-02-21 at 11 44 41 pm

**After:**
screen shot 2559-02-21 at 11 36 14 pm
screen shot 2559-02-21 at 11 31 47 pm

### CODE REVIEW

**Comment by sindresorhus** [comment]
Looks good to me. @oskarkrawczyk ?

**Comment by oskarkrawczyk** [comment]
Looks good, all clear.

**Comment by lukyth** [comment]
I fix some more places where I think they're hard to read and where I think it's not consistent with the other. Are these okay?

**Before** | **After**
---|---
old5 | new5
old6 | new6
old1 | new1
old2 | new2
old3 | new3
old4 | new4

**Comment by oskarkrawczyk** [comment]
I actually left the popovers white on purpose, as in my opinion they look better that way. I'd personally keep them white, but in the end it's @sindresorhus call.

**Comment by sindresorhus** [comment]
I think if we're going to have a dark mode it should be all in. I wouldn't want to suddenly get bright UI when chatting in the dark.

**Comment by sindresorhus** [comment]
Thank you @lukyth :)

**Pull request merged**
