### PR TITLE
Update settings menu and close button elements

### LINKED ISSUE #1806: Can't open Image Preview
Left Mouse Click a screenshot someone sent
A black screen pop-up window is brought on instead of the image

---

Caprine 2.55.4
Electron 13.6.9
linux 5.17.1-arch1-1
Locale: en-US

### LINKED ISSUE #1808: Black screen
image

He switches to a black window several times a day. It won't help you close and open it. The only option is to force kill the application or use File > Relaunch Caprine

---

Caprine 2.55.4
Electron 10.4.7
win32 10.0.22000
Locale: cs

### LINKED ISSUE #1810: Not opening pictures
All of a sudden, clicking on a picture sent by a contact in a chat doesn't open it. Instead of enlarging the picture in the window it moves into opening it, but the window stays dark (in a dark mode, of course)
Pressing escape works as if the pic was open, so the display returns to actual messaging. 

Screenshot from 2022-04-11 09-24-38

---

Caprine 2.55.4
Electron 10.4.7
linux 5.14.0-1032-oem
Locale: en-GB

### LINKED ISSUE #1811: Issue with displaying images.
I used this app for a few weeks i installed it on a few of my computers different OS from 7 to 10 . 
The issue started in recent days , when i try to open the image in full view nothing displays. It's just a blank window from the app. 
It happens on all of the computers i use.

---

Caprine 2.55.4
Electron 10.4.7
win32 10.0.19044
Locale: pl

### LINKED ISSUE #1812: Media not working
After open any media, Caprine show black sceen and nothing... ESC end it, but media still not show in "fullscreen"

image

---

Caprine 2.55.4
Electron 10.4.7
win32 10.0.22000
Locale: cs

### LINKED ISSUE #1813: images not loading
images not loading
---
steps to replicate:
1) log in to caprine for the first time windows 10
2) click on any image.
3) image is just black
image

Caprine 2.55.4
Electron 10.4.7
win32 10.0.19044
Locale: en-GB

### LINKED ISSUE #1814: Click on Screenshot/Blank Screen
Something strange two times now lately. 
1) Click on a screenshot of a Text conversation or...
2) Click on a screenshot of a Twitter conversation.
Both incidents Caprine goes to a blank screen.
The only escape is to Relaunch.

---

Caprine 2.55.4
Electron 10.4.7
win32 6.1.7601
Locale: en-US

### LINKED ISSUE #1816: Photos not opening in Linux
This is happening on both my computers on Linux. When ever I click on a photo, I just get a window full of white and I have to restart Caprine to be able to use it again. This is a new phenomenon, I only came across it today, I rarely use Facebook so am not sure when this first started. This is what it looks like when the photos fail to open

image

Everything seems to work correctly under Windows 10 

---

Caprine 2.55.2
Electron 13.6.9
linux 5.15.28-1-MANJARO
Locale: en-GB

### PR DESCRIPTION
**Pull request by mquevill**
When the button to close the preferences is not defined properly, the preferences never "close" (still invisible), hence the `hide-preferences-window` class is not removed.

Closes #1806
Closes #1808
Closes #1810
Closes #1811
Closes #1812
Closes #1813
Closes #1814
Closes #1816

### CODE REVIEW

**Comment by mquevill** [comment]
One report that it fixed the issue: https://github.com/sindresorhus/caprine/issues/1812#issuecomment-1099494539

**Comment by sindresorhus** [comment]
Thanks :)

However, the build is currently failing and I won't be able to release this until that is resolved: https://github.com/sindresorhus/caprine/runs/6065282349?check_suite_focus=true

**Comment by mjeveritt** [comment]
> However, the build is currently failing and I won't be able to release this until that is resolved: https://github.com/sindresorhus/caprine/runs/6065282349?check_suite_focus=true

Any ETA on when this can happen!? :)

**Comment by frozenpandaman** [comment]
Hoping for an update/release soon! Any clue what's going wrong, @sindresorhus?

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/caprine/releases/tag/v2.55.5

**Comment by frozenpandaman** [comment]
Hurrah, thanks a ton!

**Pull request merged**
