### PR TITLE
Resize image previews to fit in screen

### PR DESCRIPTION
**Pull request by sadmanf**
Referring to issue #851 

Small fix to make sure that image previews are resized based on the window size.

### CODE REVIEW

**Comment by sadmanf** [comment]
BEFORE:
image

AFTER:
image

**Comment by whitecrownclown** [comment]
I'd use `max-width` instead. If you send an image you'll see the `Forward/Reply` actions on the left. Using `width` will automatically push these to the left-side of the chat (which means you can't really click them) instead of the immediate left of the image itself.

maxwidth
width

**Comment by rachelyhe** [comment]
Made the quick change to `max-width: 100%`, should solve any alignment issues.

**Comment by rachelyhe** [comment]
Sorry for the random updates. Was working on the wrong branch.

**Comment by CvX** [comment]
Hmm, doesn't seem to work in all cases:

a gif in a conversation

The message element (`.3zvs`) has a reduced width but the actual image inside it exceeds its bounds.

**Comment by rachelyhe** [comment]
It looks like the div containing the react button, "GIPHY", etc. has the class `_3zvs` which was resized in the changes above, but there is a _**second**_ div which has a custom-generated width and height. Within this hard value div is an img with `class="_mxz img"` and `max-width: 100%; width: 100%;`. 

Looks like this might be a much bigger change, selecting all img with `class="_mxz img"` and changing their parents to `width=100%; height=100%` so that it fits within the bounds of `_3zvs`.

**Comment by sadmanf** [comment]
I looked through the codebase to see where an appropriate place would be for adding this change. I first thought to look through the message callbacks and perform this operation every time a gif was sent. But doing a check every time a message is sent seems to be a needlessly expensive operation. I don't think an interval-based check would be quite appropriate for this either.

Setting the parent div to `display: flex` correctly resizes the image, but there is sometimes unwanted white space below the image that I can't seem to get rid of (pictured below).
image


Any thoughts on how to proceed from here?

**Comment by sindresorhus** [comment]
@whitecrownclown ⬆️

**Comment by whitecrownclown** [comment]
That's because the container has values for both `width` and `height`.

This works alright for me:

```css
._3zvs {
	max-width: 100%;
}

/* Only match for elements that have style attributes `width` and `height` */
._41ud [style*="height"][style*="width"] {
	width: auto !important;
	height: auto !important;
}
```

before
after

**Comment by sindresorhus** [comment]
Ping @sadmanf

**Pull request closed without merging**
