### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by GEROGIANNIS**
A Better Looking README.md

### CODE REVIEW

**Comment by mquevill** [comment]
My main concern with this would be the hash links generated for each certain section. With simple names, the names are intuitive: [/caprine#install](https://github.com/sindresorhus/caprine#install). With the names with emoji in them, some of the behavior is weird: [/caprine#-highlights](https://github.com/GEROGIANNIS/caprine#-highlights), [/caprine#%EF%B8%8F-install](https://github.com/GEROGIANNIS/caprine#%EF%B8%8F-install), etc.

**Comment by GEROGIANNIS** [comment]
wow , why marked as spam? If you didnt like the features you can just close the pull request (╥﹏╥)

**Comment by dusansimic** [comment]
This pr is consistent with spammy behavior that happened during Hacktoberfest during previous years. If you'd like to contribute with something like this, open an issue and discuss it first. Only obvious bug/documentation fixes that show some effort are accepted without opening issues.

**Comment by GEROGIANNIS** [comment]
> Only obvious bug/documentation fixes that show some effort are accepted without opening issues.

Oke , now it makes sense. Tnx \(^-^)/♡

**Pull request closed without merging**
