### PR TITLE
Add TouchBar support

### PR DESCRIPTION
**Pull request by cawa-93**
image
image

#170

### CODE REVIEW

**Comment by sindresorhus** [comment]
Nice! Thanks for starting this :)

I think it would be nice to also include the profile picture in the button to make it faster to visually scan the different conversations.

**Comment by cawa-93** [comment]
@sindresorhus It may not be so easy to implement:
1. It seems that there is no possibility to display in the button two icons: the avatar and the marker of the new message.
2. The button icon should be [nativeImage](https://github.com/electron/electron/blob/master/docs/api/native-image.md)

**Comment by CvX** [comment]
@cawa-93 wouldn't it be possible to create nativeImage icons on the fly (using `nativeImage.createFromBuffer()` or `nativeImage.createFromDataURL()`) by composing a new message marker onto an avatar image?

**Comment by cawa-93** [comment]
@sindresorhus I do not know how to do this with minimal loss in performance (Without the use of canvas, etc.)

**Comment by sindresorhus** [comment]
> I do not know how to do this with minimal loss in performance (Without the use of canvas, etc.)

It wouldn't cause any noticeable performance loss. It's just combining a few tiny avatar images together with a "new message" marker. That can easily be done with `<canvas>`, for example: https://github.com/sindresorhus/caprine/blob/967f2202be7e3dd5c537b9220470867381b3fddb/browser.js#L112 We could cache the avatars, so they're only generated once per session. But it's not a blocker for this PR if you don't want to do it (?). It can be done later. This PR is already awesome.

**Comment by cawa-93** [comment]
Maybe sometime later

**Comment by sindresorhus** [comment]
Thank you, @cawa-93! 

I've opened a new issue about showing avatars: https://github.com/sindresorhus/caprine/issues/430

**Pull request merged**
