### PR TITLE
Add Dark Mode

### PR DESCRIPTION
**Pull request by oskarkrawczyk**
Since I'm a huge fan of night modes figured I'll add one to Caprine.

You can toggle it from the Electron/Caprine menu item:

screen shot 2016-01-31 at 08 55 52

Quick preview of how it looks:

screen shot 2016-01-31 at 08 55 46

Obviously the sheer amount of random-looking class names is a bit scary, hope FB doesn't change them too often.

### CODE REVIEW

**Comment by sindresorhus** [comment]
This is really awesome! :)

Would you be up for committing to maintaining the night mode? E.g. if the selectors needs updating. I don't think I will have time for that. Would be happy to add you as a maintainer if so.

What do you think about adding a keyboard shortcut for activating night mode?

I've opened a [request](https://github.com/atom/electron/issues/4300) to expose the OS X Dark Mode info in Electron. That way we could activate night mode automatically when OS X is in Dark Mode.

**Comment by oskarkrawczyk** [comment]
Sure, I'll be sticking to using Caprine until FB releases their native IM (which is to believed they're working on). So I have no problem maintaining the Night Mode.

An additional shortcut sounds cool. My suggestion would be `CmdOrCtrl+d` :-)

Also, I'm thinking on renaming Night Mode to Dark Mode, just to have consistency with OS X, what do you think?

**Comment by sindresorhus** [comment]
:+1: to both questions.

**Comment by oskarkrawczyk** [comment]
@sindresorhus Added the keyboard shortcut, fixed a few outstanding color issues, and I think we're ready to push this out the doors!

**Comment by sindresorhus** [comment]
> Also, I'm thinking on renaming Night Mode to Dark Mode, just to have consistency with OS X, what do you think?

Could you do this too?

**Comment by oskarkrawczyk** [comment]
Ah, damn, completely forgot about this.

**Comment by oskarkrawczyk** [comment]
@sindresorhus Done

**Comment by sindresorhus** [comment]
Awesome! The dark mode is really nice. I'll be using it as default :)

https://github.com/sindresorhus/caprine/releases/tag/v1.0.0

**Comment by amilajack** [comment]
The cask version should also be updated:

https://github.com/caskroom/homebrew-cask/blob/master/Casks/caprine.rb

**Comment by sindresorhus** [comment]
@vinkla Would you be able to update it?

**Comment by vinkla** [comment]
@sindresorhus sure, I'll update it.

**Pull request closed without merging**
