### PR TITLE
Fix small graphical glitch on message header

### LINKED ISSUE #368: Small graphical glitch on message header
Please add a bit more space under the conversation header (Last seen time) like on messenger.com. Application would be more elegant with this small change :)
smallglitch

### PR DESCRIPTION
**Pull request by whitecrownclown**
@sindresorhus I've removed the unrelated changes caused by prettier.

Fixes #368

### CODE REVIEW

**Comment by CvX** [comment]
The "narrow" titlebar has been Caprine's look since the first commit, but if @sindresorhus gives it a green light - I've tried the PR and it's ready to be merged. 👍

**Comment by sindresorhus** [comment]
The correct fix to #368, is not to change the size of the header. The header is intentionally this size. The correct fix is to adjust to header title to look more even.

**Comment by whitecrownclown** [comment]
@sindresorhus I've updated the PR. It looks more like the screenshot from #368

**Comment by CvX** [comment]
Before:
screen shot 2019-02-14 at 21 30 09
After:
screen shot 2019-02-14 at 21 31 09

Looks good to me

**Comment by sindresorhus** [comment]
Thanks :)

**Pull request merged**
