### PR TITLE
Hide settings icon

### PR DESCRIPTION
**Pull request by pkuczynski**
As per @sindresorhus request in https://github.com/sindresorhus/caprine/pull/975#issuecomment-507060295

### CODE REVIEW

**Comment by sindresorhus** [comment]
This is causing the avatar to be under the traffic lights on macOS:

Screen Shot 2019-07-12 at 15 45 08

**Comment by pkuczynski** [comment]
Hmm, I am not experiencing this issue. Is this your own avatar @sindresorhus?

**Comment by sindresorhus** [comment]
Yes

**Comment by pkuczynski** [comment]
Then you must be having a newer/older version of messenger. Can you check whats the class for this avatar?

**Comment by pkuczynski** [comment]
@sindresorhus your issue is fixed in #995

**Pull request merged**
