### PR TITLE
Keep aspect ratio when resizing the video call window

### LINKED ISSUE #371: Keep video aspect ratio when resizing the video chat window
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/caprine/issues/371)

A minor cosmetic tweak: 
Would be nice whenever you resize the video call window, not to have the horizontal or vertical black bars.
Screws with your OCD constantly having to resize it to make it just right.
+ dynamic resizing of the end call, mute and other buttons.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($60.00)
### Submitted pull Requests
- [#871 Keep aspect ratio when resizing the video call window](https://issuehunt.io/r/sindresorhus/caprine/pull/871)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/caprine/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by hellodavie**
Hey,

This focuses on issue #371. When the user resizes the video call window, the aspect ratio will now be maintained.

However, I'm unsure if the screen should automatically resize if the other person suddenly changes aspect ratio (eg rotating their phone during the video call, and thus changing the video orientation). Currently it will only maintain aspect ratio if the user manually resizes the window. What are your thoughts? 

Fixes #371

### CODE REVIEW

**Comment by sindresorhus** [comment]
// @theserdzo @gurrrung @PicchiKevin Can you try this out and give feedback?

**Comment by gurrrung** [comment]
I can't pull this PR locally, doing
`git fetch upstream pull/871/head:371` doesn't work.

**Comment by hellodavie** [comment]
Might have been the force push messing up the commit history, so I've reverted it. It should work now.

**Comment by sindresorhus** [comment]
I've decided to close this. The solution turned out much more complex than I expected and I don't really want to maintain this code for such a tiny UX improvement that I don't even need. Also, none of the people that requested this has bothered to try it out. Sorry for the wasted work, @hellodavie. You will obviously still get the bounty.

**Pull request closed without merging**
