### PR TITLE
Fix settings menu

### PR DESCRIPTION
**Pull request by reganlawton**
Resolves issue with settings menu / `cmd + ,` not working due to invalid selector. Working resolve for issue #911.

### CODE REVIEW

**Comment by sindresorhus** [comment]
The Settings menu is working for the new design. If you're on the old design, there's not much we can do. Hopefully Facebook will fully roll out the new design soon.

**Comment by reganlawton** [comment]
I modified the code to support the both the old and the new rollout, using th fulling selector `._30yy._6ymd._2agf,._30yy._2fug._p`.

That will support both rollouts.

**Comment by CvX** [comment]
> I modified the code to support the both the old and the new rollout, using th fulling selector 

@reganlawton Can you push that change? 🙂

**Comment by CvX** [comment]
ping @sindresorhus 🙂

**Comment by reganlawton** [comment]
@CvX Any ideas about this?

**Comment by CvX** [comment]
@sindresorhus can we push this one out as 2.31.3/2.32.0?

**Comment by sindresorhus** [comment]
@CvX I’m out, but feel free to merge and do a release (Just run `npm run release`).

**Comment by CvX** [comment]
Released 2.32.3

**Pull request merged**
