### PR TITLE
New tray icons

### PR DESCRIPTION
**Pull request by jimmy213**
I added a grey version of the icon (using a b&w filter) to show that there aren't any unread messages, and I put the old icons to show that there are new messages.

### CODE REVIEW

**Comment by jimmy213** [comment]
I built it earlier today to see how it really looks and personally I'll keep that way.

No new message
caprine_new

New message arrived
caprine_new2

**Comment by sindresorhus** [comment]
I think the gray icon should be slightly darker gray.

**Comment by jimmy213** [comment]
Yes, a darker one looks a bit nicer. Something like that?

caprine_new3

**Comment by sindresorhus** [comment]
Perfect

**Comment by alekksander** [comment]
and gradient stays?

**Pull request merged**
