### PR TITLE
Windows support

### LINKED ISSUE #2: Windows support
- [ ] Adjust the build script to build Windows app. Eg. `--platform=darwin --arch=x64` => `--all`.
- [ ] Icon. Need a `Icon.ico` file. https://github.com/maxogden/electron-packager#packageropts-callback
- [ ] Adjust the menu. Keyboard shortcuts are already cross-platform. Just need to make sure it's windowsy.
- [ ] Configure the `--version-string` in the build script. https://github.com/maxogden/electron-packager#packageropts-callback
- [ ] Ensure everything works as expected
- [ ] Add `brew install wine` to `Dev` section in the readme: https://github.com/maxogden/electron-packager#building-windows-apps-from-non-windows-platforms

### PR DESCRIPTION
**Pull request by iiegor**
This resolves #2

### CODE REVIEW

**Comment by kevva** [comment]
Works nice!



The icon in the menubar looks really weird on Windows. I know it has nothing to do with the PR, but still...

**Comment by iiegor** [comment]
@kevva Thanks for the feedback!

Yes you're right, the icon looks bad... I think instead of calling *Icon.png* when creating the **BrowserWindow** (see: [index.js#L35](https://github.com/sindresorhus/caprine/blob/master/index.js#L35)) we should use Icon.ico (result: img)

Regarding the window size issue when opening preferences, I couldn't reproduce it :confused:

**Comment by sindresorhus** [comment]
Thanks! Now available https://github.com/sindresorhus/caprine/releases/tag/0.2.0 :)

**Comment by kevva** [comment]
Sweet, nice job!

**Pull request closed without merging**
