### PR TITLE
Fix new conversation icon on narrow window size

### PR DESCRIPTION
**Pull request by pkuczynski**
Before:

Screenshot 2019-06-29 at 23 34 02

After:

Screenshot 2019-06-29 at 23 58 04

### CODE REVIEW

**Comment by pkuczynski** [comment]
I was thinking about it, but decided to go for smaller icons as otherwise the alignment of the left panel against header and conversation area is broken. I felt we should keep it as in original (full width) layout. Don’t you think?

And why would we remove the settings icon? It feels quite useful on the narrow view. I know messenger is hiding the icon but find it quite strange, don’t you think?

**Comment by CvX** [comment]
Caprine hides the Settings button in both narrow and wide views (because we aim to provide all its functionality via native app menu and keyboard shortcuts).

I believe the fact it isn’t hidden in the new Messenger UI is an omission.

**Comment by pkuczynski** [comment]
Changed to as per @CvX request.

**Comment by pkuczynski** [comment]
By the way, current version of Caprine with new FB layout does not hide settings icon anymore. Should I fix it?

**Comment by sindresorhus** [comment]
Yes

**Comment by pkuczynski** [comment]
Here you go @sindresorhus #979

**Pull request merged**
