### PR TITLE
Revert "Add rpm to Linux targets"

### PR DESCRIPTION
**Pull request by dusansimic**
This reverts commit 53241a24fa910ea935635f03ab793c043f877d12.

Rpm packages are already maintained in a third party [copr](https://copr.fedorainfracloud.org/coprs/dusansimic/caprine/) repository.

### CODE REVIEW

**Comment by lefterisgar** [comment]
It's fixed now, no need to merge.

**Review by lefterisgar — COMMENTED** [review]
I dropped the commit and did a rebase.

**Comment by dusansimic** [comment]
> It's fixed now, no need to merge.

Great! I just opened this since it's good practice to see the progress of development of features and some reasons why things are done the way they are by having discussions in the pr. Also it gives time for other developers and maintainers to give their review. That way we could avoid some breaking changes and even have better solutions.

**Comment by lefterisgar** [comment]
> > It's fixed now, no need to merge.
> 
> Great! I just opened this since it's good practice to see the progress of development of features and some reasons why things are done the way they are by having discussions in the pr. Also it gives time for other developers and maintainers to give their review. That way we could avoid some breaking changes and even have better solutions.

I see, I just felt guilty for cluttering the commit history without any apparent reason! 😅
Let's hope nobody is gonna see this!

**Pull request closed without merging**
