### PR TITLE
Hidden dialog issue Fix

### LINKED ISSUE #2096: cannot remove or forward anymore
Cannot remove messages or forward messages in latest version( 2.59.1)

---

Caprine 2.59.1
Electron 24.8.6
linux 6.5.6-76060506-generic
Locale: en-US

### LINKED ISSUE #2098: Some broken menus
The following menus does not work when clicked. 
* Preferences
* Security Alerts
* Restricted Accounts as well as Add People
* View Security alerts

### LINKED ISSUE #2100: No Camera or Preferences on Ubuntu (Snap Classic)
I'm running 2.59.1 via `snap classic install` on Ubuntu. There are two issues:

1. No access to camera, so video calls fail.
2. The CTRL + , menu does not appear. Probably due to blocked pup-ups?

These feel like security issues, but there is not access to the Chrome settings inside Electron.

### LINKED ISSUE #2106: Reaction emojis is unintentionally heart emoji on click
Upon clicking the reaction button on a message, it automatically select the heart emoji and exits the reaction popup menu immediately. This seems to mostly happen after a refresh of the Caprine page (pressing F5).

See screencast video:
[Screencast from 01-03-2024 12:38:32 PM.webm](https://github.com/sindresorhus/caprine/assets/25148816/e7cd402e-fe91-4fc7-a610-7aa51e2653df)

### LINKED ISSUE #2113: End-to-end encrypted chat PIN code dialog hidden
It seems the app prevents the PIN code modal from opening so I cannot enter the PIN code to decrypt messages.

OS: Debian 12
Installation: deb package

### PR DESCRIPTION
**Pull request by stkrknds**
Hello. Changed/updated some selectors in order to fix the hidden dialog issue.

Fixes #2106.
Fixes #2100(?) (not sure about the camera part)
Fixes #2098.
Fixes #2096.
Edit: Fixes #2113.

### CODE REVIEW

**Comment by sgtcoder** [comment]
Confirmed Messenger Settings works from the File Menu.

**Comment by giannistolou** [comment]
When will this pull request go live?

**Comment by stkrknds** [comment]
> When will this pull request go live?

Hi @giannistolou. I don't know exactly when. Only maintainers can merge prs.

**Comment by sgtcoder** [comment]
Welcome to use my merged version for the time being, notifications also fixed too

https://github.com/sgtcoder/caprine/releases

**Comment by mquevill** [comment]
I was able to replicate all listed issues except #2106 on Linux or Mac. The changes in this PR seem to fix all of the listed issues. I would assume that it also addresses the reaction issues too.

**Pull request merged**
