### PR TITLE
Fix dark mode on new Messenger UI

### PR DESCRIPTION
**Pull request by dusansimic**
Enable Facebook dark mode when option is turned on and add patches to the integrated dark mode.

Closes: #1452

### CODE REVIEW

**Comment by eyadsibai** [comment]
any chance this gets released?

**Comment by StanczakDominik** [comment]
It would indeed be lovely to get a bugfix release, if it's not too much trouble :slightly_smiling_face:

**Comment by BalintFarkas** [comment]
Would really appreciate a bugfix release, too.

**Comment by jlanzobr** [comment]
The dark mode settings need to be toggled off and back on every time Caprine 2.52 is started.

**Comment by dusansimic** [comment]
@jlanzobr #1525

**Pull request merged**
