### PR TITLE
Upgrade `electron-builder`

### PR DESCRIPTION
**Pull request by sindresorhus**
Waiting on answer on https://github.com/electron-userland/electron-builder/issues/1751

### CODE REVIEW

**Comment by sindresorhus** [comment]
@develar Building Linux app on macOS doesn't seem to work: https://travis-ci.org/sindresorhus/caprine/builds/251271992

```
{:timestamp=>"2017-07-07T19:17:14.335689+0000", :message=>"Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag", :level=>:warn}
{:timestamp=>"2017-07-07T19:17:14.763461+0000", :message=>"Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag", :level=>:warn}
{:timestamp=>"2017-07-07T19:17:15.185954+0000", :message=>"Process failed: gtar failed (exit code 2). Full command was:[\"gtar\", \"-C\", \"/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/package-dir-staging-2cc895abc0bac66c9a4968415842cda735f63860d3477813c8c0e36771f5\", \"-J\", \"--numeric-owner\", \"--owner\", \"0\", \"--numeric-owner\", \"--group\", \"0\", \"-cf\", \"/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/package-deb-build-1267574d640b16542ecb5490475b4adb568e98a291cd9b13698d54c71fcd/data.tar.xz\", \".\"]", :level=>:error}
    at /Users/travis/build/sindresorhus/caprine/node_modules/electron-builder-util/src/util.ts:64:16
    at ChildProcess.exithandler (child_process.js:277:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Socket.stream.socket.on (internal/child_process.js:340:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
From previous event:
    at exec (/Users/travis/build/sindresorhus/caprine/node_modules/electron-builder-util/src/util.ts:42:3)
    at /Users/travis/build/sindresorhus/caprine/node_modules/electron-builder/src/targets/fpm.ts:207:11
    at Generator.next (<anonymous>)
From previous event:
    at FpmTarget.build (/Users/travis/build/sindresorhus/caprine/node_modules/electron-builder/out/targets/fpm.js:260:11)
    at default.each.it (/Users/travis/build/sindresorhus/caprine/node_modules/electron-builder/src/platformPackager.ts:103:87)
From previous event:
    at taskManager.addTask.default.map.then (/Users/travis/build/sindresorhus/caprine/node_modules/electron-builder/src/platformPackager.ts:103:35)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/Users/travis/build/sindresorhus/caprine/node_modules/electron-builder/src/platformPackager.ts:103:8)
    at /Users/travis/build/sindresorhus/caprine/node_modules/electron-builder/src/platformPackager.ts:98:10
From previous event:
    at LinuxPackager.pack (/Users/travis/build/sindresorhus/caprine/node_modules/electron-builder/out/platformPackager.js:159:11)
    at /Users/travis/build/sindresorhus/caprine/node_modules/electron-builder/src/packager.ts:230:24
From previous event:
    at Packager.doBuild (/Users/travis/build/sindresorhus/caprine/node_modules/electron-builder/out/packager.js:303:11)
    at /Users/travis/build/sindresorhus/caprine/node_modules/electron-builder/src/packager.ts:161:52
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Packager.build (/Users/travis/build/sindresorhus/caprine/node_modules/electron-builder/out/packager.js:222:11)
    at /Users/travis/build/sindresorhus/caprine/node_modules/electron-builder/src/builder.ts:256:40
    at Generator.next (<anonymous>)
    at build (/Users/travis/build/sindresorhus/caprine/node_modules/electron-builder/out/builder.js:69:21)
    at Object.args [as handler] (/Users/travis/build/sindresorhus/caprine/node_modules/electron-builder/src/cli/cli.ts:41:4)
    at Object.self.runCommand (/Users/travis/build/sindresorhus/caprine/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/Users/travis/build/sindresorhus/caprine/node_modules/yargs/yargs.js:1018:24)
    at Object.get [as argv] (/Users/travis/build/sindresorhus/caprine/node_modules/yargs/yargs.js:927:19)
    at Object.<anonymous> (/Users/travis/build/sindresorhus/caprine/node_modules/electron-builder/src/cli/cli.ts:36:15)
From previous event:
    at build (/Users/travis/build/sindresorhus/caprine/node_modules/electron-builder/out/builder.js:69:21)
    at Object.args [as handler] (/Users/travis/build/sindresorhus/caprine/node_modules/electron-builder/out/cli/cli.js:114:9)
    at Object.self.runCommand (/Users/travis/build/sindresorhus/caprine/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/Users/travis/build/sindresorhus/caprine/node_modules/yargs/yargs.js:1018:24)
    at Object.get [as argv] (/Users/travis/build/sindresorhus/caprine/node_modules/yargs/yargs.js:927:19)
    at Object.<anonymous> (/Users/travis/build/sindresorhus/caprine/node_modules/electron-builder/out/cli/cli.js:110:314)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by develar** [comment]
Is there a reason why do you don't want to use provided example config and build all on macOS? Why not build Linux on Linux, since it is possible and config tested and provided for you? And saves time of macOS Travis agents for other opensource projects?

**Comment by sindresorhus** [comment]
It's simpler to just build on one platform. Less config. Less chance of build problems.

**Comment by develar** [comment]
I don't fully agree with you, I don't see major problems to use Travis CI Linux agent to build linux-related. And it also will not use free macOS agents — pool is limited and it is better to use only if necessary. But... yes. It maybe convenient to to work with exactly one agent and think only about on OS (e.g. if something failed, you just see the only agent result).

I will investigate what's wrong with gtar on Travis CI. Sorry for delay.

**Comment by develar** [comment]
Should be fixed in the 19.22.4 (it is `next` release). Test added and it is green. https://travis-ci.org/develar/caprine/builds/265677164 is still not finished (yeach, agent pool is limited).

If 19.22.4 will not fix issue for you, please set env in the travis settings: `DEBUG=electron-builder`.

**Comment by develar** [comment]
No, not fixed yet.

**Comment by develar** [comment]
Fixed in 19.24.0.

**Comment by sindresorhus** [comment]
@develar I tried updating to the latest `electron-builder`, but I'm getting another error now: https://travis-ci.org/sindresorhus/caprine/builds/293062301

**Comment by develar** [comment]
@sindresorhus glib statically linked now, please try 19.42.2

**Comment by sindresorhus** [comment]
Great! Thanks for all the help @develar :)

**Pull request merged**
