### PR TITLE
Private mode for new Messenger UI

### PR DESCRIPTION
**Pull request by dexter93**
First attempt on this. Currently just blurring everything

Any feedback welcome

### CODE REVIEW

**Comment by dusansimic** [comment]
This blurs whole message view including message input and all of the buttons. That's also the case for contact list. It would be better if it would blur just the profile pictures, sent images and videos and message bubbles instead of every element on the page.

**Comment by sindresorhus** [comment]
@dexter93 Bump

**Comment by dusansimic** [comment]
@sindresorhus is the goal of private mode to blur everything except messages (what it does on old UI IIRC) or everything including messages (what this does). I'm already working on something so I'd like to know how to proceed.

Also I've been overwhelmed by work on my University so that's why I've been slow with fixing issues.

**Comment by sindresorhus** [comment]
> is the goal of private mode to blur everything except messages (what it does on old UI IIRC) or everything including messages (what this does). I'm already working on something so I'd like to know how to proceed.

Make chat's anonymous for anyone looking, meaning blurring avatars and names.

**Pull request closed without merging**
