### PR TITLE
WIP: Enable copy image context menu item

### PR DESCRIPTION
**Pull request by whitecrownclown**
Related to #904 

@sindresorhus 	Anything else we might add to the context menu?

Thanks!

### CODE REVIEW

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/caprine/issues/904 is about copying the image itself, not its URL.

**Comment by sindresorhus** [comment]
`Related to #904` => `Fixes #904` so the issue is auto-closed when the PR is merged.

**Comment by whitecrownclown** [comment]
@sindresorhus Oh, my bad. I misunderstood. I'll update the PR.

**Comment by sindresorhus** [comment]
Would be best to do a PR to Electron-context-menu to add it.

**Comment by FreeOoI** [comment]
The important thing is to be able to copy (also with a keyboard shortcut command) from a tab an img/vids like the browser behaviour. Atm, the only solution is to save the files and manually transfer it or copy from your OS to paste it somewhere.

**Comment by sindresorhus** [comment]
@whitecrownclown Can you finish the PR? Re: https://github.com/sindresorhus/electron-context-menu/releases/tag/v0.15.0

**Comment by sindresorhus** [comment]
Actually, it's `true` by default, so I can just upgrade the dependencies.

**Pull request closed without merging**
