### PR TITLE
Fix: Cannot read property 'children' of null

### PR DESCRIPTION
**Pull request by J2TEAM**
Screenshot:
image

image

### CODE REVIEW

**Comment by dusansimic** [comment]
Is there a way to reproduce this error? I'm not experiencing it on my machine (Caprine v2.53.0).

**Comment by mquevill** [comment]
The error only comes up when the conversation list is narrow (only shows pictures, no text). Simply hovering over a conversation will raise this error. It does not appear with the wide sidebar.

**Comment by dusansimic** [comment]
I guess that querying for the correct list (only the one that is full size, not compact) would be a better solution. There might event be chat name information in compact chat that needs to be extracted in a different way. I'll research this a bit.

**Comment by sindresorhus** [comment]
Bump :)

**Pull request closed without merging**
