### PR TITLE
WIP: Reload mainWindow on system resume

### LINKED ISSUE #103: App stops updating on resume after suspend mode
Pretty rare case, not sure yet about 1.4 (just updated), but for 1.3 reproduces.

When close MBP, go to another network and open it there some time later (few hours or so) - in some cases app stops getting updates. And can't send messages in this state as well, errors returned.
When app relaunched, messages was trying to send aren't there, but works finely, with fresh history.

I understand it may be not related to the app, as a Facebook's Messenger front-end bug. But maybe it's reasonable to use the [power-monitor](https://github.com/electron/electron/blob/master/docs/api/power-monitor.md) as workaround to reload the web view on `resume`?

### PR DESCRIPTION
**Pull request by whitecrownclown**
Fixes #103 

@sindresorhus 

Right now it only checks for connection on `resume` and reloads the mainWindow.
What other behaviour would we like? I checked and `Messenger` already keeps the current message & focus. Keeping it `WIP` for now.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you check if we need to add anything [here](https://github.com/sindresorhus/caprine/blob/ed720bdb931dc005567e71b125f695e14a9b4941/package.json#L139) for this?

**Comment by sindresorhus** [comment]
This is not really a fix for #103. It's just an easy workaround. I would prefer to try to find a proper fix first. There must be a reason it stops updating. Maybe we haven't given enough permissions. Maybe we're blocking some connection. I think this needs more research.

**Comment by reganlawton** [comment]
@sindresorhus its not a fix but I've been using the same workout for like 2 month might be nice to give non-dev built users a workaround till we can solve the root issue.

**Comment by CvX** [comment]
This workaround gets a no-go from me.

I rarely have the issue where Messenger stop updating (maybe once a couple of months), but since I have full vibrancy enabled, this change would trigger the vibrancy bug every time I wake my machine up (and would have to restart the app).

**Comment by reganlawton** [comment]
That’s not a workable solution then. I personally don’t use that feature so I didn’t notice the bug.

**Comment by sindresorhus** [comment]
Like @CvX said, this workaround is not feasible until Electron fixes the vibrancy issue, and even then, I would prefer a proper fix.

**Comment by sindresorhus** [comment]
Closing as I don't see us merging this.

**Pull request closed without merging**
