### PR TITLE
Update readme.md to fix broken link on screenshot.

### PR DESCRIPTION
**Pull request by hugomd**
I've noticed this has happened across quite a few repositories, unfortunately 😢

### CODE REVIEW

**Comment by sindresorhus** [comment]
The correct fix is to use HTML for the link too. It's using `` for a reason.

**Comment by hugomd** [comment]
@sindresorhus I think GitHub changed something which broke it — I can change it to  if you'd like?

**Comment by sindresorhus** [comment]
Yes

**Comment by hugomd** [comment]
@sindresorhus Done 🎉

**Comment by sindresorhus** [comment]
Thanks :)

**Pull request merged**
