### PR TITLE
Fix icon on Linux

### PR DESCRIPTION
**Pull request by BananaManCJ**

### CODE REVIEW

**Comment by BananaManCJ** [comment]
Fixes #1213

**Comment by sindresorhus** [comment]
This should be fixed in electron-builder, not here.

**Comment by BananaManCJ** [comment]
This tells the electron builder what size the icon is, and since the size wasn't specified before, it defaulted to 0x0, making the icon unable to be used.

**Comment by sindresorhus** [comment]
electron-builder documents that it is able to generate all the needed icons from one file.

**Comment by BananaManCJ** [comment]
Closing pull request since this is allegedly is fixed with [this commit](https://github.com/ringcentral/ringcentral-embeddable-electron-app/commit/29652ab8bb8eeef0c6ee60490d0ea793dc2621ac)

**Comment by BananaManCJ** [comment]
https://github.com/electron-userland/electron-builder/issues/2577#issuecomment-621727522

**Comment by CvX** [comment]
@BananaManCJ that's just a commit to some other app.

**Comment by BananaManCJ** [comment]
> @BananaManCJ that's just a commit to some other app.

I know, but that is the way to fix it on this app. I was quoting that comment to show how to fix it on this repo.

**Comment by yermulnik** [comment]
There's a somewhat related PR in Electron that has been merged today: https://github.com/electron/electron/pull/23674

**Comment by BananaManCJ** [comment]
> There's a somewhat related PR in Electron that has been merged today: [electron/electron#23674](https://github.com/electron/electron/pull/23674)

That's for system tray icons, not the icon used in the .desktop file

**Pull request closed without merging**
