### PR TITLE
WIP: Fix privacy features

### PR DESCRIPTION
**Pull request by dusansimic**
This pr fixes two privacy features on new design: blocking typing indicator and blocking read indicators. ~It doesn't yet block delivery receipts since I haven't yet found out how they are sent (it's possible that they can't be blocked)~ It's blocking delivery receipts too and also active indicator can be blocked which is a feature that could be considered.

This is a WIP pr so it's not ready to be merged. Once it's ready to be merged I'll remove the WIP prefix in the title. I'm not sure what side effects are there but in my testing there seem to be none.

One big change here is __disabling context isolation__ on main window. This is done so Proxy of WebSocket class could be created. Otherwise it wouldn't be possible to execute code for creating a Proxy class before the native one is used. It might be a security risk so this needs to be reviewed very carefully but it is a working solution. Similar logic could be used for fetching receiving message content from which a notification could be made.

Any suggestions regarding this (or a better solution) are very welcome!

Closes: #1503

### CODE REVIEW

**Comment by ChaimGoldstein** [comment]
I don't know if this is the proper place to post issues regarding the PR. 

I recently tested out the changes made in this Pull Request. Apparently the block seen feature has an error. Apparently if i activate the said feature Caprine is unable to send any outgoing messages. However, I can still react to incoming messages. I have tested this out. Here are some screenshots as proof, thank you.

image

**Comment by dusansimic** [comment]
> if i activate the said feature Caprine is unable to send any outgoing messages

I'm aware of this but thanks for the report. I've haven't had time to work on this properly so it's currently in this broken state. Once I've fixed it and everything works as expected, I'll ping again for testing if that's fine.

**Comment by ChaimGoldstein** [comment]
> > if i activate the said feature Caprine is unable to send any outgoing messages
> 
> I'm aware of this but thanks for the report. I've haven't had time to work on this properly so it's currently in this broken state. Once I've fixed it and everything works as expected, I'll ping again for testing if that's fine.

Thank you, I also noticed that it flags messages received the first time you load up Caprine. Probably because of a limitation too, I guess.

**Comment by mavaa** [comment]
Hi, just found out about caprine and went stragiht for this PR as the seen blocker is the only thing I'm after 🙃 

What I found out:
- "seen" blocking works 🎉 
- Sending does not with blocking enabled, but:
- You can turn off blocking to send messages 🎉 

Even if I send the message with the blocker on, it seems like it will retry with a given interval until i turn it back off, and then successfully send it if I wait long enough. I did not experience any messages being marked as read when I started the application the first time, so that issue might be unrelated(?)

Could a workauroud for sending messages simply be to turn the block setting off and on again when a message is sent (if the option was enabled in the first place)? I would argue that sending a response is more or less a read receipt in itself.

**Comment by AggelosM** [comment]
> Could a workauroud for sending messages simply be to turn the block setting off and on again when a message is sent (if the option was enabled in the first place)? I would argue that sending a response is more or less a read receipt in itself.

This could be a solution. And we could just mark the blocking option as "Experimental".

**Comment by dusansimic** [comment]
> This could be a solution. And we could just mark the blocking option as "Experimental".

I'd prefer if we implemented the full feature and not and experimental workaround which is more of a hack than a workaround. I haven't really had free time for this to complete it and I'm not sure when I will. If anyone else is interested in doing this, go ahead, I've planned on doing something similar that's done in AlexStackDev's extension.

Currently privacy features are done by parsing websocket messages with regex which is not ideal and a bit hacky. I'd prefer to completely parse the websocket message like it's done in the mentioned extension but that would be a significant amount of work. Once those messages are parsed, I guess it could be possible to extract the received message contents and create a notifications on for received messages.

**Comment by Amandaville** [comment]
> AlexStackDev's extension

Can you please provide a link to this extension?  I have searched and cannot find anything by that name.  Does it provide a "Block Seen Indicator" function for Messenger?

**Comment by sindresorhus** [comment]
Any movement on this?

**Comment by dusansimic** [comment]
> Any movement on this?

Not for some time, no. Feel free to close this if there's no one to take over. If at some point I find some free time (currently there is none at all) I'll get back to this and get it done.

**Comment by Amandaville** [comment]
Does closing this issue mean that it's finally fixed after all this time?  I don't see a newer release than December 2021 and this was just closed.  When can we expect the updated release with these fixes to the privacy features?

**Comment by TheWiresharkGuy** [comment]
Hi, is it fixed with [v2.55.5](https://github.com/sindresorhus/caprine/releases/tag/v2.55.5)?

**Pull request closed without merging**
