### PR TITLE
Hide additional attributes in private mode

### PR DESCRIPTION
**Pull request by mquevill**
- Change titlebar element (both name and picture)
- Read indicators (in group chats, the indicators that aren't the last one are controlled differently)

### CODE REVIEW

**Comment by dusansimic** [comment]
For me, the name and profile pictures of the chat are not blured in the right sidebar. It would be good to have that blured to in case someone likes to use Caprine with right sidebar open.

**Comment by mquevill** [comment]
@dusansimic Makes sense. I'll blur those too. On the right sidebar, should the "Chat Members" expandable list be blurred too? Or should that be up to the user to keep closed?

Also, I'm working on fixing an issue when chat colors are set to a gradient:
image

**Comment by dusansimic** [comment]
> Or should that be up to the user to keep closed?

I think this will be fine. It's more useful to leave it as is and close it if user want's to hide it.

**Comment by mquevill** [comment]
Summary of what's changed now:
- Added: Hide name label on message (group chat)
- Added: Read indicators in message
- Added: Name, picture, and active status in right sidebar
- Adjusted: Read indicators in message list
- Adjusted: Titlebar name and picture

**Review by dusansimic — APPROVED** [review]

**Comment by dusansimic** [comment]
Thanks @mquevill! Facebook likes to change Messenger frontend every now and then and these features tend to break quite often lately 😅

**Pull request merged**
