### PR TITLE
Fix Caprine features on new UI

### PR DESCRIPTION
**Pull request by dusansimic**
This is a PR for fixing all Caprine features on the new UI. All fixed features are checked in the list below.

- [ ] File menu
	- [x] New conversation
	- [ ] Caprine settings
		- [ ] Privacy
		- [ ] Emoji style
		- [ ] Autoplay videos
		- [ ] Show message preview in notifications (⚠ not supported by new desing)
		- [ ] Mute notifications
		- [ ] Mute call ringtone
		- [ ] Show Unread Badge
		- [x] Spell checker
		- [x] Hardware acceleration
		- [x] Always on top
		- [x] Auto hide menu bar
		- [ ] Flash Window on message
		- [x] Show tray icon
		- [x] Launch minimized
		- [x] Quit on Window close
		- [x] Custom CSS
	- [x] Messenger settings (this is not showing all options in preferences for some odd reason, the regular way to open preferences shows all options)
	- [ ] Switch to Work Chat
	- [x] Log Out
	- [x] Relaunch Caprine
	- [x] Quit
- [x] Edit menu
- [ ] View menu
	- [x] Reset text size
	- [x] Increase text size
	- [x] Decrease text size
	- [x] Dark Mode (#1500)
	- [ ] Hide names and avatars (#1492)
	- [ ] Sidebar
	- [ ] Show Message Buttons
	- [x] Show active contacts
	- [x] Show message requests
	- [x] Show hidden threads
- [x] Conversation menu
	- [x] Mute conversation
	- [x] Hide conversation
	- [x] Delete conversation
	- [x] Select next conversation
	- [x] Select previous conversation
	- [x] Find conversation
	- [x] Insert GIF
	- [x] Insert Sticker
	- [x] Insert Emoji
	- [x] Attach files
	- [x] Focus text input
	- [x] Spell checker
- [x] Help menu

### CODE REVIEW

**Comment by dusansimic** [comment]
@sindresorhus, what do you think about this way of fixing things (just throwing in if statements everywhere to check if user has the new design). Other solution would be making two function for each feature (one for new design and one for old and calling them separately. That might be cleaner but it worries me that there would be a lot of duplicate code. What is your opinion on this?

**Comment by sindresorhus** [comment]
> what do you think about this way of fixing things (just throwing in if statements everywhere to check if user has the new design).

Seems ok.

**Comment by sindresorhus** [comment]
@dusansimic Maybe we should merge this now, do a release, and then you can continue the rest of the items in a new PR? Just to get the fixes out there.

**Comment by dusansimic** [comment]
> @dusansimic Maybe we should merge this now, do a release, and then you can continue the rest of the items in a new PR? Just to get the fixes out there.

Agreed. I'm making this a regular pr and I'll start working on other issues in specific PR-s for each issue from now on.

**Comment by sindresorhus** [comment]
Can you make the titlebar draggable on the new design? I don't think we can ship it before that's done as the window cannot be moved.

**Comment by dusansimic** [comment]
Yeah, I don't have a Mac but there was already an issue open about this #1488. Does this seem fine or should we hide the profile picture and the Chats label. Since I don't have a Mac, maybe we should do the cosmetic fixes later?

**Comment by sindresorhus** [comment]
We can do the cosmetic fixes later.

**Comment by dusansimic** [comment]
I've added the CSS styles from the issue I've mentioned. Please check if it works.

**Comment by sindresorhus** [comment]
Nice work!

**Comment by maxoku** [comment]
Show Unread Badge isn't fixed, it was for some time, but isn't working anymore.

**Pull request merged**
