### PR TITLE
Add ability to customize the user interface colors and styles

### LINKED ISSUE #535: Violet variant for Dark Mode
Hi 
I would like to see another choice of background and text colours. I guess the dark-mode.css
is inside the content_resources_200_percent.pak; so not accessible (?) for tweakers. I don't know how it would look like but here are some choices changed from the file dark-mode.css at github
Violet Background - Orange Text ( White text, as is already, may be better though):
violet-mode.css 
---------------------------------------------------------------------------------------------------------
:root {
		--base: #FF4800
		--base-ninety: rgba(255, 72, 0, 0.9);	
		--base-seventy-five: rgba(255, 72, 0, 0.75);
		--base-seventy: rgba(255, 72, 0, 0.7);
		--base-fifty: rgba(255, 72, 0, 0.5);
		--base-fourty: rgba(255, 72, 0, 0.4);
		--base-thiry: rgba(255, 72, 0, 0.3);
		--base-twenty: rgba(255, 72, 0, 0.2);
		--base-five: rgba(255, 72, 0, 0.05);
		--base-ten: rgba(255, 72, 0, 0.1);
		--base-nine: rgba(255, 72, 0, 0.09);
		--container-color: #33192C;
		--conversation-bg: rgb(51, 25, 44);
		--list-header-color: #3A2033;
		--blue: #00E1FF;
		--unread-bg: #243B66;
}
the rest leave as is I guess?
caprine_33192cb

-------------------------------------------------------------------------------------------------------
By the way, line 8 "thiry" would have to be "thirty" ?
Thanks for your great work. All the best Rolf

### PR DESCRIPTION
**Pull request by dusansimic**
Added custom styles feature. This feature is meant for power users and it uses a css file that is injected when Caprine starts.

---

Fixes #535

### CODE REVIEW

**Comment by mzso** [comment]
Nothing I changed in the CSS has any effect. Also the advanced menuitem seems to have disappeared for good. It didn't come back even after I deleted the custom.css file. I'm at a loss.

**Comment by CvX** [comment]
The "Advanced" menu item isn't displayed conditionally, it's always there. I can't think of any scenario where it wouldn't be. 😅

Are you sure you're still running the latest version of Caprine?

**Comment by mzso** [comment]
[**@CvX**](https://github.com/CvX) commented on [2019. jan. 29. 22:57 CET](https://github.com/sindresorhus/caprine/pull/651#issuecomment-458723378 "2019-01-29T21:57:39Z - Replied by Github Reply Comments"):
> The "Advanced" menu item isn't displayed conditionally, it's always there. I can't think of any scenario where it wouldn't be. <g-emoji class="g-emoji" alias="sweat_smile" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f605.png">sweat_smile</g-emoji>
> 
> Are you sure you're still running the latest version of Caprine?

Well, the scenario was I expected that caprine overwrote the old version but it didn't so I started the old version. :)

Now I sort of started to get it working, but the changes only effect the dark theme. And it looks like none of the listed elements the background color of the messages I send.

Is there some sort of guide for styling? Or at least a comprehensive list of elements?

**Comment by CvX** [comment]
> Well, the scenario was I expected that caprine overwrote the old version but it didn't so I started the old version. :)

Ha! Mystery solved! 😄

> Now I sort of started to get it working, but the changes only effect the dark theme. And it looks like none of the listed elements the background color of the messages I send.
> 
> Is there some sort of guide for styling? Or at least a comprehensive list of elements?

Unfortunately there no such guide or any list. Your best shot is to explore Messenger's interface using DevTools and look for the classes you need (e.g. messages you send are `._43by`)

**Comment by mzso** [comment]
[**@CvX**](https://github.com/CvX) commented on [2019. jan. 30. 01:08 CET](https://github.com/sindresorhus/caprine/pull/651#issuecomment-458758771 "2019-01-30T00:08:46Z - Replied by Github Reply Comments"):
> > Well, the scenario was I expected that caprine overwrote the old version but it didn't so I started the old version. :)
> 
> Ha! Mystery solved! <g-emoji class="g-emoji" alias="smile" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f604.png">smile</g-emoji>
> 
> > Now I sort of started to get it working, but the changes only effect the dark theme. And it looks like none of the listed elements the background color of the messages I send.
> > 
> > Is there some sort of guide for styling? Or at least a comprehensive list of elements?
> 
> Unfortunately there no such guide or any list. Your best shot is to explore Messenger's interface using DevTools and look for the classes you need (e.g. messages you send are `._43by`)

Ouch. I had trouble even finding your example. And it seems there are about for other classes listed for the element besides this. Makes it rather complicated.

**Comment by dusansimic** [comment]
@mzso I'd recommend going through `dark-theme.css` since it has commented styles and it might help you with what you want.

**Comment by mzso** [comment]
[**@dusansimic**](https://github.com/dusansimic) commented on [2019. jan. 30. 20:13 CET](https://github.com/sindresorhus/caprine/pull/651#issuecomment-459071008 "2019-01-30T19:13:34Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso) I'd recommend going through `dark-theme.css` since it has commented styles and it might help you with what you want.

Good idea. Thanks. I assume you mean dark-mode.css.

**Pull request merged**
