### PR TITLE
Add Tomorrow themes for code blocks

### LINKED ISSUE #107: Improve the look of code blocks
They look pretty ugly by default, and would be nice to have a different style in dark mode.

Follow-up to https://github.com/sindresorhus/caprine/issues/105.

### PR DESCRIPTION
**Pull request by Bo-Duke**
Fixes #107 

Every class defined in Facebook's code blocks stylesheet is redefined so there shouldn't be any problem.

I chose Tomorrow because it is one the most famous code schemes out there but of course it can be done with other ones.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you use CSS variables for the colors? So it's easier to update it in the future. Example: https://github.com/sindresorhus/caprine/pull/211/files

**Comment by sindresorhus** [comment]
Can you add something about this feature in the readme? To the [Features](https://github.com/sindresorhus/caprine#features) and [Highlights](https://github.com/sindresorhus/caprine#highlights) sections.

**Comment by Bo-Duke** [comment]
Sorry for the delay, very busy month!

I added CSS variables (and wow, for the dark theme it's so much simpler)
I wasn't inspired at all for the readme though and I don't have a retina display so the screenshot doesn't look as good as the other ones.

**Comment by sindresorhus** [comment]
Looks amazing. Thanks for working on this @Bo-Duke :)

**Comment by Bo-Duke** [comment]
Thank you, it was actually my first real pull request so it means a lot :D

**Comment by sindresorhus** [comment]
Congrats! It was a very good one.

**Pull request merged**
