### PR TITLE
Fix new design user menu

### PR DESCRIPTION
**Pull request by dusansimic**
This patch fixes the query selector for user menu on new design.

Checklist:
- [x] Fix user menu query
- [x] Check for new design
- [x] Clean up selectors

Closes: #1909 
Closes: #1859
Closes: #1918 
Closes: #1923

### CODE REVIEW

**Comment by dusansimic** [comment]
So here's a progress update. Right now I'm wrestling with typescript config because some packages that I'm bumping in this pr (for example `element-ready`) have switched to ES module system which is now causing trouble because for some reason, electron is importing our source code as a commonjs module. I'm still trying to figure out how to manage this but if anyone has any info or some examples, help is very welcome.

**Comment by dusansimic** [comment]
One solution that seems to work for some people is splitting the build process for main electron code, preloaded electron code and renderer code. All of those parts are build with vite and tsc ([repo](https://github.com/cawa-93/vite-electron-builder)). It's worth looking into since it would clean up the code structure a bit and it might be a bit easier to maintain. That would however require adding a few extra steps to the build process.

**Comment by dusansimic** [comment]
A short term solution could be an user set preference for the new desing (if users have the new design, they can just chech the option in advanced settings in menu bar). It would require user intervention but it would fix the issue for now without refactoring the code to vite + tsc.

**Review by lefterisgar — APPROVED** [review]
It seems to fix said issues. Looks good to me!

**Comment by dusansimic** [comment]
@lefterisgar if you still have access to the old sidebar design, please test weather checking for new design works. It should work okay with openning and closing the preferences and it should remove the `hide-preferences-window` class once it's done.

**Comment by lefterisgar** [comment]
> @lefterisgar if you still have access to the old sidebar design, please test weather checking for new design works. It should work okay with openning and closing the preferences and it should remove the `hide-preferences-window` class once it's done.

Unfortunately I don't have access to it anymore. I think it has rolled out to most users out there.

**Comment by lefterisgar** [comment]
Is this ready to merge?

**Comment by dusansimic** [comment]
> Is this ready to merge?

Essentially yes, I'd just like to complete the last task from the list in this pr. I'll see if I can do it today.

**Pull request merged**
